name: Build and push Docker image

on:
  push:
    branches:
    - 'master'
  workflow_dispatch:

jobs:
  docker:
    name: Build and Push Docker image to Docker Hub
    # Only run if the commit message contains the string [build-docker]
    if: contains(github.event.head_commit.message, '[build-docker]')
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    # Read the version
    - name: Read version
      run: echo "VERSION=$(cat OpenBullet2.Web/version.txt)" >> $GITHUB_ENV
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        file: ./Dockerfile.remote
        platforms: linux/arm/v7,linux/arm64/v8,linux/amd64
        tags: openbullet/openbullet2:latest,openbullet/openbullet2:${{ env.VERSION }}
